### PR TITLE
convert caustics, cornell_box_disney scenes to new bsdf

### PR DESCRIPTION
**Pull request by tigrazone**
image

### CODE REVIEW

**Comment by yuphin** [comment]
Thanks for adapting the old code. The branch (including the BSDF code) is still WIP so I'll have a look once everything else is sorted out.

**Comment by tigrazone** [comment]
> still WIP
But your renderer is impressive. I'm waiting for your new commits.
Looks good. 
Disney/principal bsdf well implemented here https://github.com/knightcrawler25/GLSL-PathTracer

**Comment by yuphin** [comment]
Thanks for the PR, I've adapted most of your changes with some modifications. There were a couple of flags missing while parsing Mitsuba materials so I've also adjusted them and I couldn't observe any ringing so far (Although things are still WIP).
I'll close the PR for now and will address the remaining stuff pointed out in the issues.

**Comment by tigrazone** [comment]
for example, bedroom scene doesnt converted well.
Look at glasses/dielectrics near mirror or lamp.
curtains doesnt convert well

**Pull request closed without merging**
